//! Persist verified `PackageExternalizationHint` rows into
//! `package_externalization_hints`. The matcher and the
//! `package-externalization-hints` subcommand both compute hints and
//! hand them to `persist_package_externalization_hints` to write.
//!
//! Owns the table's `CREATE` SQL, the per-row insert/upsert, and the
//! policy-version constant that distinguishes hints generated by
//! different safety proofs.

use std::collections::BTreeSet;

use rusqlite::{Connection, params};

use crate::errors::MatchPackagesError;

pub(crate) const PACKAGE_EXTERNALIZATION_HINT_POLICY_VERSION: i64 = 1;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct PackageExternalizationHint {
    pub(crate) package_name: String,
    pub(crate) package_version: String,
    pub(crate) entry_path: String,
    pub(crate) export_specifier: String,
    pub(crate) content_hash: Option<String>,
    pub(crate) normalized_source_hash: Option<String>,
    pub(crate) public_members: BTreeSet<String>,
    pub(crate) proof_policy_version: Option<i64>,
}

pub(crate) fn persist_package_externalization_hints(
    connection: &mut Connection,
    hints: &[PackageExternalizationHint],
) -> Result<usize, MatchPackagesError> {
    ensure_package_externalization_hints_table(connection)?;
    let transaction = connection
        .transaction()
        .map_err(MatchPackagesError::WritePackageExternalizationHints)?;
    let mut written = 0usize;
    for hint in hints {
        let public_members_json = serde_json::to_string(
            &hint.public_members.iter().collect::<Vec<_>>(),
        )
        .map_err(|source| {
            MatchPackagesError::WritePackageExternalizationHints(
                rusqlite::Error::ToSqlConversionFailure(Box::new(source)),
            )
        })?;
        written += transaction
            .execute(
                r"
                INSERT INTO package_externalization_hints
                    (package_name, package_version, entry_path, export_specifier,
                     content_hash, normalized_source_hash, public_members_json,
                     proof_policy_version, created_at, updated_at)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, datetime('now'), datetime('now'))
                ON CONFLICT(package_name, package_version, entry_path, export_specifier)
                DO UPDATE SET
                    content_hash = excluded.content_hash,
                    normalized_source_hash = excluded.normalized_source_hash,
                    public_members_json = excluded.public_members_json,
                    proof_policy_version = excluded.proof_policy_version,
                    updated_at = datetime('now')
                ",
                params![
                    hint.package_name.as_str(),
                    hint.package_version.as_str(),
                    hint.entry_path.as_str(),
                    hint.export_specifier.as_str(),
                    hint.content_hash.as_deref(),
                    hint.normalized_source_hash.as_deref(),
                    public_members_json.as_str(),
                    hint.proof_policy_version
                        .unwrap_or(PACKAGE_EXTERNALIZATION_HINT_POLICY_VERSION),
                ],
            )
            .map_err(MatchPackagesError::WritePackageExternalizationHints)?;
    }
    transaction
        .commit()
        .map_err(MatchPackagesError::WritePackageExternalizationHints)?;
    Ok(written)
}

fn ensure_package_externalization_hints_table(
    connection: &Connection,
) -> Result<(), MatchPackagesError> {
    connection
        .execute_batch(PACKAGE_EXTERNALIZATION_HINTS_CREATE_SQL)
        .map_err(MatchPackagesError::WritePackageExternalizationHints)
}

const PACKAGE_EXTERNALIZATION_HINTS_CREATE_SQL: &str = r"
CREATE TABLE IF NOT EXISTS package_externalization_hints (
    package_name TEXT NOT NULL,
    package_version TEXT NOT NULL,
    entry_path TEXT NOT NULL,
    export_specifier TEXT NOT NULL,
    content_hash TEXT,
    normalized_source_hash TEXT,
    public_members_json TEXT NOT NULL DEFAULT '[]',
    proof_policy_version INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (package_name, package_version, entry_path, export_specifier),
    CHECK (TRIM(package_name) != ''),
    CHECK (TRIM(package_version) != ''),
    CHECK (TRIM(entry_path) != ''),
    CHECK (TRIM(export_specifier) != ''),
    CHECK (content_hash IS NULL OR TRIM(content_hash) != ''),
    CHECK (normalized_source_hash IS NULL OR TRIM(normalized_source_hash) != ''),
    CHECK (
        content_hash IS NOT NULL
        OR normalized_source_hash IS NOT NULL
        OR TRIM(public_members_json) NOT IN ('', '[]')
    )
);
CREATE INDEX IF NOT EXISTS idx_package_externalization_hints_package
    ON package_externalization_hints(package_name, package_version);
";
