//! Set of JavaScript-host identifiers treated as runtime globals.
//!
//! Used by free-identifier scans to filter out names that are always
//! resolvable at runtime (`Array`, `Promise`, `console`, ...). Extracted
//! verbatim from `lib.rs`.

pub(crate) fn is_runtime_global_identifier(identifier: &str) -> bool {
    matches!(
        identifier,
        "AbortController"
            | "AbortSignal"
            | "AggregateError"
            | "Array"
            | "ArrayBuffer"
            | "BigInt"
            | "BigInt64Array"
            | "BigUint64Array"
            | "Blob"
            | "Boolean"
            | "Buffer"
            | "Bun"
            | "ByteLengthQueuingStrategy"
            | "CompressionStream"
            | "CountQueuingStrategy"
            | "CustomEvent"
            | "DataView"
            | "Date"
            | "DecompressionStream"
            | "DOMException"
            | "Error"
            | "Event"
            | "EventTarget"
            | "EvalError"
            | "File"
            | "FinalizationRegistry"
            | "Float32Array"
            | "Float64Array"
            | "FormData"
            | "Function"
            | "Headers"
            | "Infinity"
            | "Int16Array"
            | "Int32Array"
            | "Int8Array"
            | "Intl"
            | "JSON"
            | "Map"
            | "Math"
            | "NaN"
            | "Number"
            | "Object"
            | "Promise"
            | "Proxy"
            | "RangeError"
            | "ReadableStream"
            | "ReferenceError"
            | "Reflect"
            | "RegExp"
            | "Request"
            | "Response"
            | "Screen"
            | "Set"
            | "String"
            | "Symbol"
            | "SyntaxError"
            | "TextDecoder"
            | "TextDecoderStream"
            | "TextEncoder"
            | "TextEncoderStream"
            | "TransformStream"
            | "TypeError"
            | "URIError"
            | "URL"
            | "URLSearchParams"
            | "Uint16Array"
            | "Uint32Array"
            | "Uint8Array"
            | "Uint8ClampedArray"
            | "WeakMap"
            | "WeakRef"
            | "WeakSet"
            | "WebSocket"
            | "WritableStream"
            | "__dirname"
            | "__filename"
            | "atob"
            | "browser"
            | "btoa"
            | "chrome"
            | "clearImmediate"
            | "clearInterval"
            | "clearTimeout"
            | "console"
            | "crypto"
            | "decodeURI"
            | "decodeURIComponent"
            | "document"
            | "encodeURI"
            | "encodeURIComponent"
            | "eval"
            | "exports"
            | "fetch"
            | "global"
            | "globalThis"
            | "isFinite"
            | "isNaN"
            | "localStorage"
            | "location"
            | "module"
            | "navigator"
            | "onmessage"
            | "parseFloat"
            | "parseInt"
            | "performance"
            | "process"
            | "queueMicrotask"
            | "require"
            | "self"
            | "setImmediate"
            | "setInterval"
            | "setTimeout"
            | "structuredClone"
            | "undefined"
            | "unescape"
            | "window"
            | "XMLHttpRequest"
    )
}
